name: PHP Composer

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.1']
        symfony-version: ['^5.0', '^6.0']
    name: PHP ${{ matrix.php-versions }} Test with Symfony ${{ matrix.symfony-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install test dependencies
      run: composer require --dev symfony/twig-bundle:${{ matrix.symfony-version }} symfony/framework-bundle:${{ matrix.symfony-version }} symfony/web-profiler-bundle:${{ matrix.symfony-version }}

    - name: Run phpunit tests
      run: ./vendor/bin/phpunit

    - name: Run behat tests
      run: ./vendor/bin/behat
